# Numerical Python(Numpy) - Part 1

In [1]:
# de facto standard (사실상의 표준)
import numpy as np # 기본시작


In [2]:
a = [1, 2, 3]
a * 3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [4]:
list(map(lambda x: 3*x, a))

[3, 6, 9]

In [5]:
b = np.array([1,2,3])
b*3

array([3, 6, 9])

## 1. Numpy Dimensional array

In [7]:
a = np.array([1,4,5,8], float)
a

array([1., 4., 5., 8.])

In [8]:
type(a)

numpy.ndarray

In [9]:
a.dtype, a.shape

(dtype('float64'), (4,))

## 2. Array shape

In [11]:
# Vector (1차원)
vec = np.array([1,4,5,8])
vec.shape

(4,)

In [14]:
# Matrix (2차원)
matrix = np.array([[1,2,3], [4,5,6]])
print(matrix.shape)
print(matrix)      # 보기쉽게 정렬

(2, 3)
[[1 2 3]
 [4 5 6]]


In [17]:
# Tensor(3차원 이상)
tensor = np.arange(1,25).reshape(2,3,4)
print(tensor)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [20]:
vec.shape, matrix.shape, tensor.shape

((4,), (2, 3), (2, 3, 4))

In [22]:
# element의 갯수
vec.size, matrix.size, tensor.size

(4, 6, 24)

In [23]:
# data type
# float 뒤에 숫자는 bit를 의미
a = np.array([1,2,3], dtype=np.float32) 
a                                       # dtype = << 생략가능

array([1., 2., 3.], dtype=float32)

In [24]:
b = np.array([1,2,3], np.int16)
b

array([1, 2, 3], dtype=int16)

reshape

In [25]:
matrix.shape

(2, 3)

In [26]:
matrix.reshape(6,)

array([1, 2, 3, 4, 5, 6])

In [27]:
matrix.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [28]:
# -1은 numpy가 알아서 맞춰줌 (단, size가 동일)
matrix.reshape(-1,)

array([1, 2, 3, 4, 5, 6])

In [29]:
matrix.reshape(3,-1)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [30]:
matrix.reshape(3,-1).shape

(3, 2)

In [32]:
tensor.reshape(4,-1).shape

(4, 6)

In [40]:
matrix.reshape(-1,)   # 1차원

array([1, 2, 3, 4, 5, 6])

In [34]:
matrix.reshape(1,-1)    # 2차원

array([[1, 2, 3, 4, 5, 6]])

In [35]:
matrix.reshape(-1,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

## flatten

In [36]:
tensor.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [37]:
tensor.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [41]:
tensor.reshape(-1,)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

## 3.Indexing & Slicing

In [42]:
matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
matrix[0][1]

2

In [44]:
matrix[0,1]    # numpy에서 가능

2

In [45]:
tensor[1,1,2]

19

slicing

In [47]:
b = np.arange(16).reshape(4,-1)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [48]:
# 5,6,9,10  뽑아내기
b[1:3, 1:3]

array([[ 5,  6],
       [ 9, 10]])

In [50]:
# 5,6,7,9,10,11 뽑아내기
b[1:3,1:]

array([[ 5,  6,  7],
       [ 9, 10, 11]])

In [52]:
# 1,3,9,11
b[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [59]:
X, y = b[:,:-1],b[:, -1]
X.shape, y.shape

((4, 3), (4,))