1.

In [2]:
import numpy as np
a = np.array([[10,20,30,40],[50,60,70,80]])
a

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [64]:
# 강사님 풀이
np.arange(1,9).reshape(2,4) * 10

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

2.

In [68]:
m = np.arange(15).reshape(3,5)
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [12]:
#1)
print(m[m==7])
#2)
print(m[m==14])
#3)
print(m[1,1:3])
#4)
print(m[1:3,2])
#5)
print(m[:2,3:])

[7]
[14]
[6 7]
[ 7 12]
[[3 4]
 [8 9]]


In [69]:
# 강사님 풀이
m[1,2], m[-1,-1]
m[1,1:3]
m[1:,2]
m[:2,3:]

array([6, 7])

3.

In [14]:
m = m.flatten()
m

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [24]:
#1)
print(m[m%3 == 0])
#2)
print(m[m%4==1])
#3)
print(m[(m%3==0)*(m%4==1)])

[ 0  3  6  9 12]
[ 1  5  9 13]
[9]


In [ ]:
# 강사님 풀이
m[m%3==0]
m[m%4==1]
m[np.logical_and(f%3==0, f%4==1)]

4.

In [26]:
a = np.eye(5,5)*2 + np.eye(5,5,1) + np.eye(5,5,-1)*3
a

array([[2., 1., 0., 0., 0.],
       [3., 2., 1., 0., 0.],
       [0., 3., 2., 1., 0.],
       [0., 0., 3., 2., 1.],
       [0., 0., 0., 3., 2.]])

5.

In [29]:
a = np.random.randint(0, 11, 30).reshape(5,6)
a

array([[10,  4,  5,  0,  3,  6],
       [ 4,  0,  9,  0,  5,  7],
       [ 4, 10,  7,  9,  4,  5],
       [ 8,  8,  5,  0,  7,  6],
       [ 8,  1,  0,  7,  5,  8]])

In [ ]:
# 강사님
np.random.seed(2021)
m = np.random.uniform(0,10,30).reshape(5,6).round(4)
m

In [36]:
#1)
print(a.max())
#2
print(a.sum(axis=1))
#3
print(a.max(axis=1))
#4
print(a.mean(axis=0))
#5
print(a.min(axis=0))

10
[28 25 39 34 29]
[10  9 10  8  8]
[6.8 4.6 5.2 3.2 4.8 6.4]
[4 0 0 0 3 5]


6.

In [70]:
score = np.array([[1,2,3,4],[46,99,100,71],[81,59,90,100]])
score

array([[  1,   2,   3,   4],
       [ 46,  99, 100,  71],
       [ 81,  59,  90, 100]])

In [ ]:
np.sort(score)

In [71]:
s = np.argsort(score[1])
s

array([0, 3, 1, 2])

In [72]:
# 내림차순
s[::-1]

array([2, 1, 3, 0])

In [73]:
score[:,s[::-1]]

array([[  3,   2,   4,   1],
       [100,  99,  71,  46],
       [ 90,  59, 100,  81]])

In [ ]:
# 한 줄로
score[:,np.argsort(score[1])[::-1]]

In [48]:
np.sort(m[1,:],)[::-1]

array([100,  99,  71,  46])

7.

In [56]:
m = np.random.randint(1,7,100)
print(m.mean())

3.31


In [ ]:
#강사님
np.random.seed(2021)
dice = np.random.randint(1,7,100)
dice
np.mean(dice)

8.

In [63]:
 m = np.random.randn(0,0.01,250)
 m


TypeError: ignored